---
# Persistent Volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sam-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
# Mongo Service
# This service does not have a type field. 
# If a Service does not have a type field, Kubernetes assigns it the default type ClusterIP.
# ClusterIP makes the Pod accessible from within the cluster, but not from outside 
# — this is fine because the only entity that has to access the MongoDB Pod is the app.
apiVersion: v1
kind: Service
metadata:
  name: sam-service-mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
# Mongo Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam-mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: sam-mongo-pvc