apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  ports:
  - nodePort: 30442
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
  # match the labels... app: nginx - let the service know which microservice it is connecting with
    app: nginx
  type: NodePort

  # three types of svc - cluster-ip - nodeport - loadbalancer